# Generated by Django 5.1.3 on 2024-11-27 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='sub_category',
            new_name='subcategory',
        ),
    ]
